### ISSUE TITLE
Implement module for obtaining a user's response.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#262]
## Background

For certain situations, the user's input should be requested. Examples of such includes;
- When a remote node requests to create a transport to the local node. The local node should ask the user whether (s)he will allow this action to happen.
- When an app wishes to reserve/listen on a port.

However, currently the user is not informed, and actions are performed immediately.

## Description

The proposal is to implement a module named `human`; located in `/internal/human`. This module will be responsible for requesting user-action.

```golang
package human

// UserOption is an option given to a user.
type UserOption struct {
    Label string
    Color color.Color
}

// InputGrabber is responsible for obtaining user input.
type InputGrabber interface {
    // GrabInput obtains the users input.
    GrabInput(ctx context.Context, msg, details string, opts []UserOption) (UserOption, error)
}
```

Initially, we want 4 implementations of `InputGrabber`.

- `CommandLineGrabber` requests for user input via `stdin` and `stdout` of the executable.
- `WebsocketGrabber` requests for user input via an http interface exposing websocket connections.
- `MultiGrabber` combines multiple `InputGrabber` implementations, where the first user response of every request is accepted.

## Tasks
- [x] Implement as specified above.
- [x] Request for user permission when accepting remote-initiated transports.
- [x] Request for user permission when app attempts to listen on a port.
- [x] Write tests.
