### ISSUE TITLE
Refactor 'skywire-cli'.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#264]
## Background

Currently, commands are mostly `skywire-node`-specific (although not fully). It will be good to split commands into groups that identify the service that the command interacts with.

For example, commands that interact with `skywire-node` should be under `skywire-cli node <command>`.

## Tasks
- [ ] Mode all commands that interact with `skywire-node` as sub-commands under the `skywire-cli node` command. These commands should be located in `/cmd/skywire-cli/commands/node`.

- [ ] Move commands interacting with `messaging-discovery` as sub-commands under the `skywire-cli mdisc` command. These commands should be located in `/cmd/skywire-cli/commands/mdisc`.

- [ ] Move commands interacting with `route-finder` as sub-commands under the `skywire-cli rtfind` command.

- [ ] Move commands interacting with `transport-discovery` as sub-commands under the `skywire-cli tpdisc` command.

- [ ] Update the associated documentation in `README.md`.

**Comment by evanlinjin** [comment]
@mungujn

**Comment by jdknives** [comment]
Closed by #270
