### ISSUE TITLE
Re-implement app-related commands in skywire-cli and manager-node.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#321]
> Branch: `mainnet-dev`

## Background
After the separation of the proc and app concepts (Where a proc is an instance of a running app), the interfaces; `node.RPC` and `node.RPCClient` (as well as their implementations) need an update. And consequently, also the endpoints of `manager.Node` and `skywire-cli`.

## Tasks
- [x] Replace the commented out methods of `node.RPC`/`node.RPCClient` with the following methods:
  - `Apps() []app.Meta` obtains all available apps.
  - `StartProc(appName string, args []string, port uint16) (router.ProcID, error)` runs a proc.
  - `StopProc(pid router.ProcID) error` stops a proc.
  - `ListProcs() []router.ProcInfo` lists all running procs. Note that `ProcInfo` is not implemented; it should be a combination of `router.ProcID` ,`app.Meta` and `app.ExecConfig`.

- [x] Write sub-commands for the aforementioned calls in `skywire-cli`.
- [ ] Write endpoints for the aforementioned calls in `manager.Node`.
