### ISSUE TITLE
[ROUTING] Remove 'transport.Manager' dependency from 'setup.Node'.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#442]
Setup Node should not be using `transport.Manager`, and should use `dmsg.Client` directly.

**Tasks:**
- [x] Remove `transport.Manager` from `setup.Node` completely.
- [x] Come up with plan as to how this is to be tested.
- [x] Refactor current tests to be more understandable (or remove them).

**Comment by evanlinjin** [comment]
@nkryuchkov from my understanding, based on how `setup.Node` is designed, we should be able to create a client structure (`setup.Client`). This should make the code interacting with `setup.Node` easier to use.

**Comment by nkryuchkov** [comment]
@evanlinjin Thanks for the advice, good idea. I'll create it.
