### ISSUE TITLE
[ROUTING] Add 'purpose' fields in transport.Transport and transport.Factory

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#486]
## Context
So the following is given:
- All services is to communicate via #dmsg in the future (including hypervisor).
- We need some way of diferentiating between the "purpose" of each transport (whether it is responsible for setting-up a data transport, communication between hypervisor and visor, etc).

## Proposed Solution
Hence, I propose the following:
1. A transport has a **type** and a **purpose**.
    - **type** is the implementation of the transport. E.g. `dmsg`.
    - **purpose** is the purpose of the given transport.
2. Add additional `purpose string` field to `(transport.Factory).Dial`. Also have a new method `(transport.Transport).Purpose() string` that returns the transport's purpose.

In regards to how this will be implemented in `dmsg`, we can add an additional field to `REQUEST` and `ACCEPT` fields. I propose we change the payload of `REQUEST` and `ACCEPT` frames to contain a JSON structure as follows:

```golang
type HandshakePayload struct {
    Version string `json:"version"` // just in case the struct changes.
    InitPK cipher.PubKey `json:"init_pk"`
    RespPK cipher.PubKey `json:"resp_pk"`
    Purpose string `json:"purpose"`
}
```

## Alternative Solutions
- The current solution is keeping a list of public keys that are associated with the transports purpose. However, this will not be enough for the future.
- We can also introduce a handshake that needs to occur for every transport, however that will be complicated.
- We can also prefix every transport packet, however that will not be idea.

## Tasks
- [x] Change interfaces to aforementioned.
- [x] Change `dmsg` repo to have `purpose` in `REQUEST` and `ACCEPT` frames.
- [x] Change structures in `/pkg/transport/dmsg` to satisfy the aforementioned interfaces.

**Comment by jdknives** [comment]
Outdated by https://github.com/skycoin/dmsg/issues/28
