### ISSUE TITLE
Implement ability to switch between transport types (dmsg and tcp transport).

### ISSUE THREAD

**Issue by ayuryshev** [skycoin/skywire-testnet#501]
**Feature description**

Implement ability to specify between different underlying network connection types when saving transports.

**Important notes**

Communication between setup nodes and visor nodes **SHOULD ALWAYS** be via `dmsg.`
Electable network types should only be done for transports.

**Tasks**

These tasks should be done in the given order.

- [ ] Branch from [`mainnet-milestone1`](https://github.com/skycoin/skywire/tree/mainnet-milestone1).
- [ ] Move `TCPTransport` stuff to [`pkg/network`](https://github.com/skycoin/skywire/tree/mainnet-milestone1/pkg/network) module.
- [ ] Add needed fields to `network.Config`.
- [ ] Add `tcpC` member to `network.Network`.
- [ ] Add needed actions to `Network.Init()` (if needed).
- [ ] Add needed actions to `Network.Close()`.
- [ ] Add `Network.TCP() *TCPFactory` field.
- [ ] Modify `Network.Dial()` and `Network.Listen()` to be able to dial/listen with `"tcp"`.
- [ ] Add `"tcp"` options to:
  - https://github.com/skycoin/skywire/blob/b5909ebadb24f19f3f66a83f764fc2fa36b0e997/pkg/visor/visor.go#L134
  - https://github.com/skycoin/skywire/blob/b5909ebadb24f19f3f66a83f764fc2fa36b0e997/pkg/visor/visor.go#L154
- Add `public-key:ip-address` table to `visor.Config` which in turn gets copied to `network.Config` and then used by `network.TCPFactory`.
- [ ] Add interactive tests to use `TCPFactory`.
